language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# db configurations
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE teststudentapi;" -U postgres
  - psql -c "CREATE USER testuser WITH PASSWORD '1234';" -U postgres
# command to run tests
script: nose2
